openapi: "3.0.1"

info:
  title: "User Authentication Service - API"
  version: "1.1.0"
  description: |
    API specifications for the User Authentication service.
    This spec includes:
    - Header-based user creation (username, email, password in headers)
    - User retrieval & search endpoints
    - 400, 401, 404, 409, 500 error responses
    - JWT tokens expose only `userCode` (UUID) as `sub` claim

servers:
  - url: http://localhost:8083/authentication_service/api
    description: Local Development Server

tags:
  - name: User
    description: All user-related operations
  - name: Auth
    description: JWT Token-related operations

paths:
  /user:
    post:
      tags:
        - User
      summary: Create a new user (via headers)
      operationId: createUser
      description: |
        Creates a new user using headers instead of request body.
        Required headers: username, email, password.

        Server will generate a `userCode` (UUID) and return it in the response body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User successfully created (returns created user with server-generated userCode)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
              examples:
                created:
                  summary: Example user creation response
                  value:
                    userCode: "8a8f9b2e-1f3c-4d2a-9f3a-abcdef123456"
                    username: "alice"
                    email: "alice@example.com"
                    role: "USER"
        '400':
          description: Invalid input or missing required headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                missingHeader:
                  summary: Missing header example
                  value:
                    code: 400
                    message: "Missing required header: password"
        '409':
          description: Username or email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                conflict:
                  value:
                    code: 409
                    message: "Username or email already exists"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      tags:
        - User
      summary: Get User by userCode
      operationId: getUserByUserCode
      parameters:
        - name: userCode
          in: query
          description: Unique user code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


  /users/search:
    get:
      tags:
        - User
      summary: Search users by username or email
      operationId: searchUsers
      description: |
        Allows searching users by username or email.
        At least one query parameter is required.
      parameters:
        - name: username
          in: query
          required: false
          schema:
            type: string
        - name: email
          in: query
          required: false
          schema:
            type: string
            format: email
      responses:
        '200':
          description: List of matching users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
        '400':
          description: Missing search criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      tags:
        - Auth
      summary: Login with email and password
      description: Generate token on user login
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Invalid email or password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/validate:
    post:
      tags:
        - Auth
      summary: Validate JWT token
      operationId: validateToken
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer access token
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
          '200':
            description: Token is valid
          '401':
            description: Token is invalid or expired
          '500':
            description: Internal server error


components:
  schemas:
    CreateUserRequest:
      type: object
      required:
        - username
        - email
        - password
        - phoneNumber
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
          pattern: '^[a-zA-Z0-9_]+$'
          description: Username for the new user (3-50 alphanumeric characters and underscores only)
        email:
          type: string
          format: email
          minLength: 5
          maxLength: 100
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          description: Email address of the new user (must be a valid email format)
          example: user@example.com
        phoneNumber:
          type: string
          pattern: '^\+[1-9]\d{1,14}$'
          minLength: 8
          maxLength: 20
          description: Phone number in E.164 format (e.g., +1234567890)
          example: "+1234567890"
        password:
          type: string
          minLength: 8
          maxLength: 100
          pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'
          description: |
            Password must be 8-100 characters long and include:
            - At least one uppercase letter
            - At least one lowercase letter
            - At least one digit
            - At least one special character (@$!%*?&)
        role:
          type: string
          enum: [USER, SUPERUSER]
          default: USER
          description: Role for the user. Default is USER

    UserResponse:
      type: object
      description: User details (password excluded intentionally)
      required:
        - username
        - email
        - phoneNumber
        - role
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
          description: Phone number in E.164 format (e.g., +1234567890)
          example: "+1234567890"
        role:
          type: string
          enum: [USER, SUPERUSER]

    ErrorResponse:
      type: object
      x-lombok-annotations:
        - "@lombok.Builder"
      properties:
        errorCode:
          type: number
          format: double
          description: Numeric error code
        description:
          type: string
          description: Human-readable description providing more details about the error
        errorType:
          type: string
          description: Categorization of the error (e.g., VALIDATION_ERROR, AUTHENTICATION_FAILED)
        errorMessage:
          type: string
          description: A brief message summarizing the error condition

    LoginRequest:
      type: object
      required: [ email, password ]
      properties:
        email:
          type: string
          format: email
          minLength: 4
        password:
          type: string
          minLength: 8

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        expiresIn:
          type: string
